import { CarnetInterface } from "../models/CarnetInterface";
import { MateriaInterface } from "../models/HorarioInterface";

export const materias: Array<MateriaInterface> = [
  {
    CODIGO_MATERIA: "TSI502",
    NOMBRE_MATERIA: "PROGRAMACION EN JAVA",
    GRUPO: "B192",
    DIA: 1,
    HORA_INICIO: "0900",
    HORA_FINAL: "1029",
    SALON: "AULA REMOTA",
    DESCRIPCION: "SEDE PRINCIPAL"
  },
  {
    CODIGO_MATERIA: "TSI502",
    NOMBRE_MATERIA: "PROGRAMACION EN JAVA",
    GRUPO: "B192",
    DIA: 1,
    HORA_INICIO: "1030",
    HORA_FINAL: "1159",
    SALON: "AULA REMOTA",
    DESCRIPCION: "SEDE PRINCIPAL"
  },
  {
    CODIGO_MATERIA: "TSI512",
    NOMBRE_MATERIA: "REDES",
    GRUPO: "D191",
    DIA: 1,
    HORA_INICIO: "1500",
    HORA_FINAL: "1629",
    SALON: "214 A",
    DESCRIPCION: "SEDE PRINCIPAL"
  }
]

export const carnet: any = {
  data: {
    C_ESTP_ID: 124623,
    C_PEGE_DOCUMENTOIDENTIDAD: "1005108571",
    C_PENG_PRIMERAPELLIDO: "GÓMEZ",
    C_PENG_SEGUNDOAPELLIDO: "DELGADO",
    C_PENG_PRIMERNOMBRE: "JOSE",
    C_PENG_SEGUNDONOMBRE: "DAVID",
    C_UNID_NOMBRE: "SEDE PRINCIPAL",
    C_PROG_NOMBRE: "TECNOLOGIA EN DESARROLLO DE SISTEMAS INFORMATICOS",
    C_FRAN_DESCRIPCION: "DIURNA",
    C_PENS_DESCRIPCION: "PENSUM TSI2019-2",
    C_PENS_TOTALCREDITOS: 108,
    C_ESTP_CREDITOSAPROBADOS: 76,
    C_AVANCE: 70.4,
    C_CATE_DESCRIPCION: "ANTIGUO",
    C_SITE_DESCRIPCION: "SOBRESALIENTE",
    C_PENG_EMAILINSTITUCIONAL: "jdgomezdelgado@uts.edu.co",
    C_ESTP_PROMEDIOGENERAL: 4.28,
    C_PEUN_FECHAFIN: "2022-06-30T05:00:00.000Z"
  },
  iat: 1655509250
}